/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package myapp.sample.app

class App {
  val greeting: String
    get() {
      return "Hello Alpha2phi!"
    }
}

fun main() {
  println(App().greeting)
}
